version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vendbot
      POSTGRES_USER: vendbot
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vendbot123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  bot:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql+asyncpg://vendbot:${DB_PASSWORD:-vendbot123}@postgres/vendbot
      REDIS_URL: redis://redis:6379
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
